### ISSUE TITLE
If I change the min_count flag in order to produce vocab of size same bert's original vocab: can I then use this new vocab to pretrain from a checkpoint, or I have to train from the scratch?

### ISSUE THREAD

**Issue by maggieezzat** [kwonmha/bert-vocab-builder#1]

**Comment by kwonmha** [comment]
You would need to train BERT from the scratch again.
It's because new vocab will have different subwords from google's open vocab and your subwords would have different index.
Corpus is tokenized based on vocab and each token is mapped to the index of vocab.
So different vocab makes different input data.

Subwords in vocab changes by the text data used to build vocab.
I haven't tried to build vocab with BookCorpus and Wikipedia google used.
But I think it's not able to get exact same vocab as google's.

**Comment by maggieezzat** [comment]
I understand that, but what if I used different data as well, I mean I have a different corpus that I used your script to generate a vocab file for, and then can I use this vocab file and the data I have to train from a checkpoint? I know I have to keep vocab_size the same as their checkpoint because it's an input to the model_fn, if I make it same size, can I catch from their checkpoint? Thank you a  lot

**Comment by maggieezzat** [comment]
Also, does that vocab builder adds words as well as subwords? or I have to add them myself?

**Comment by kwonmha** [comment]
Vocab builder doesn't add words.
Words don't need to exist in vocab, the input text to BERT is tokenized into subwords.
So you don't need to add words to vocab, you can use subword.

**Comment by maggieezzat** [comment]
> I understand that, but what if I used different data as well, I mean I have a different corpus that I used your script to generate a vocab file for, and then can I use this vocab file and the data I have to train from a checkpoint? I know I have to keep vocab_size the same as their checkpoint because it's an input to the model_fn, if I make it same size, can I catch from their checkpoint? Thank you a lot

Could you please answer that question as well?

**Comment by kwonmha** [comment]
Even though you got same vocab size, you have to train from scratch.
Let's say, you want to train a sentence "a b c".
If the sentence is mapped into "1 2 3" with vocab1, and "10 11 12" in vocab2.
You can't resume training from the model trained with vocab1.
In vocab2, index 1, 2, 3 don't mean a, b, c.

If you want to use their pretrained model, use their vocab and your data.
Your data will be tokenized based on their vocab.
Then try to start training from their checkpoint.
You don't need to build vocab again.
But I'm not sure how much the model will be fit to your data.

**Comment by maggieezzat** [comment]
Okay, thank you very much for your help =)

**Comment by tszslovewanpu** [comment]
> Even though you got same vocab size, you have to train from scratch. Let's say, you want to train a sentence "a b c". If the sentence is mapped into "1 2 3" with vocab1, and "10 11 12" in vocab2. You can't resume training from the model trained with vocab1. In vocab2, index 1, 2, 3 don't mean a, b, c.
> 
> If you want to use their pretrained model, use their vocab and your data. Your data will be tokenized based on their vocab. Then try to start training from their checkpoint. You don't need to build vocab again. But I'm not sure how much the model will be fit to your data.

Does it means that if i want to use the pre-trained model (no matter it is BERT or LlaMa or whatever Large Language Model) i can only use their original tokenizer(their vocab) , i can't re-train a vocab by adding some strange symbols my corpus contains, right? hope to get your answer, thx!

For example, there are special symbols in my corpus like $%^(supposed that they are not contained in the vocabulary of BERT_base).
