### ISSUE TITLE
Unable to understand the input format and also the generated output

### ISSUE THREAD

**Issue by ayushjain1144** [kwonmha/bert-vocab-builder#2]
I wanted to build a vocab on my corpus. I made a folder named data, put the file in it(made a small text file just for sanity check), set corpus_max_lines to 8(no.of lines in my test text) and run the following command

```
python subword_builder.py --corpus_filepatter
n=/media/ayushjain1144/"New Volume"/"IGCAR PS"/data --corpus_max_lines=8 --output_filename=/media/ayushjain1144/"New Volume"/"IGCAR PS"/out
```

The output I received is this:

```
['/media/ayushjain1144/New Volume/IGCAR PS/data']
0.00014281272888183594 for reading read file : /media/ayushjain1144/New Volume/IGCAR PS/data
read all files
61
61
61
61
```

out directory is empty. Also not able to understand what 61 means! Please help!

**Comment by kwonmha** [comment]
In your case, 61 is the size of vocabulary.
So, it seems that the vocabulary has been created.

**Comment by arunzz** [comment]
Tokenization is different from bert? After building the vocabulary, bert gives UNK for all the tokens for new sentences even if those words are present in the voabulary.

**Comment by ayushjain1144** [comment]
Thank you for your reply. I will try again and see.

Also can you give me an estimate of the time required to build a 30,000 vocabulary using around 17 million words(do i require gpu for it?)
Also I read you mentioned to play with parameters to adjust vocab size. Is there no way I can specify the size(as far as I know we can set the vocab size in sentence piece)

Thank You

**Comment by kwonmha** [comment]
I made it available on google-research's bert.
Why don't you check intermediate variable values in WordpieceTokenizer's
tokenize method?

2019년 6월 20일 (목) 오후 8:33, Arun Kumar <notifications@github.com>님이 작성:

**Comment by kwonmha** [comment]
I don't think you need gpus.
And I guess it will take about an hour.
17m corpus doesn't look large.

And since this repo is based on t2t, rather than sentencepiece, You can't specify the size.
Try reducing words from vocabulary output.
The order is sorted by descending from the top above single special characters.
