### ISSUE TITLE
Merge conflict markers are still there…

### ISSUE THREAD

**Issue by bhoomit** [kwonmha/bert-vocab-builder#3]
https://github.com/kwonmha/bert-vocab-builder/blob/2e7d107e23edb3ba9ef2b5b0fa75c84674359581/text_encoder.py#L688

**Comment by bhoomit** [comment]
https://github.com/kwonmha/bert-vocab-builder/pull/4#issue-291306156

**Comment by kwonmha** [comment]
Merged, close.
