### ISSUE TITLE
Should I match the vocabulary size with bert_config.json

### ISSUE THREAD

**Issue by AnakTeka** [kwonmha/bert-vocab-builder#6]
I'm trying to pretrain from scratch this https://github.com/google-research/bert/ and using this library to make vocab.txt, after I have successfully make a vocab.txt by using this library, should I match the size of vocabulary on bert_config.json with newly created vocab.txt?

**Comment by kwonmha** [comment]
Yes.
You need to modify the vocab size set on bert_config.json to match the number of vocabs of your newly created vocab.txt file.

**Comment by kwonmha** [comment]
Close issue as it seems no more comments are needed.
