### ISSUE TITLE
AttributeError: module 'tensorflow.io' has no attribute 'gfile'

### ISSUE THREAD

**Issue by AmeeraMilibari** [kwonmha/bert-vocab-builder#8]
Hello, 
first of all, thank you for this project

I tried to run it using tensorflow==1.11.0 and I got this error
`AttributeError: module 'tensorflow.io' has no attribute 'gfile'`

I also tried to run it using tensorflow==2.0.0 and got this error
`AttributeError: module 'tensorflow' has no attribute `'flags'`

could you list all the requirements or give a solution, thank you!

**Comment by kwonmha** [comment]
According to the tensorflow official api guide, `gfile` had been integrated into `tensorflow.io` from 1.13.
So, upgrade your tensorflow to 1.13 or maybe you can use `tf.gfile.Glob()`. 'G' is capital.
Hope this works.

**Comment by AmeeraMilibari** [comment]
worked with me, thanks!
