### ISSUE TITLE
Issue with tf.gfile / tf.io.gfile

### ISSUE THREAD

**Issue by then4p** [kwonmha/bert-vocab-builder#9]
The code in the repo does not work with either Tensorflow version 1.11 or version 2.0.  I got it to work in 1.11 by changing the code according to the [ 1.11 API ](https://www.tensorflow.org/versions/r1.11/api_docs/python/tf/gfile/Glob)
```
filenames = sorted(tf.gfile.Glob(filepattern))
  print(filenames)
  lines_read = 0
  for filename in filenames:
    start = time.time()
    with tf.gfile.Open(filename) as f:
```

Alternatively update the readme to the reflect the tf version you used.

**Comment by kwonmha** [comment]
Fixed like your code and that's what I intended to do.
Thanks for pointing out.
Maybe I got confused

**Comment by kwonmha** [comment]
Fixed like your code and that's what I intended to do.
Thanks for pointing out.
Maybe I got confused.
